export const COLLECTION_PAGE_TOP_BANNER_IMAGE = `/b1Y8SUb12gPHCSSSNlbX4nB3IKy.jpg`
export const PROFILE_PAGE_TOP_BANNER_IMAGE = `/vXpeJJs1z8OKC88CNJX9O9QOhtr.jpg`
export const MOVIE_LIST_TOP_BANNER_IMAGE = `/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg`
export const TV_LIST_TOP_BANNER_IMAGE = `/SqAZjEqqBAYvyu3KSrWq1d0QLB.jpg`
export const PERSON_LIST_TOP_BANNER_IMAGE = `/l8v3gJDlASN0lNn51gR8zQJsu5O.jpg`
